# -*- coding: utf-8 -*-
"""TieuLuanChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knLgnD9V3_MPQMAikAx3xLiqn1CAkKys
"""
from flask import Flask, request, render_template_string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# ====== Huấn luyện mô hình học máy ======
data = [
    ("giờ làm việc của bạn là gì", "working_hours"),
    ("khi nào mở cửa", "working_hours"),
    ("có làm việc cuối tuần không", "working_hours"),
    ("bạn mở cửa lúc mấy giờ", "working_hours"),

    ("chính sách hoàn tiền thế nào", "refund_policy"),
    ("tôi muốn đổi/trả hàng", "refund_policy"),
    ("trả hàng mất phí không", "refund_policy"),
    ("tôi đã mua sai, hoàn tiền được không", "refund_policy"),

    ("tôi muốn liên hệ", "contact"),
    ("làm sao để gọi cho bạn", "contact"),
    ("email hỗ trợ của bạn là gì", "contact"),
    ("số điện thoại của shop là gì", "contact"),

    ("bạn có ship không", "shipping"),
    ("phí giao hàng là bao nhiêu", "shipping"),
    ("ship COD không", "shipping"),
    ("giao hàng mất bao lâu", "shipping"),
]
texts, labels = zip(*data)
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)
clf = MultinomialNB()
clf.fit(X, labels)

# ====== Các phản hồi theo intent ======
intent_responses = {
    "working_hours": "⏰ Chúng tôi làm việc từ 8h đến 17h, từ thứ 2 đến thứ 6.",
    "refund_policy": "💸 Bạn có thể hoàn trả trong vòng 7 ngày kể từ ngày mua.",
    "contact": "📞 Bạn có thể liên hệ qua email: support@example.com hoặc gọi 0123.456.789.",
    "shipping": "🚚 Chúng tôi giao hàng toàn quốc, hỗ trợ COD và phí giao từ 20K tuỳ khu vực."
}

app = Flask(__name__)

# Giao diện HTML đơn giản
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Chatbot Messenger</title>
    <style>
        body {
            font-family: "Segoe UI", sans-serif;
            background: #f0f2f5;
            display: flex;
            justify-content: center;
            padding: 40px;
        }
        .chat-box {
            width: 400px;
            background: white;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0,0,0,0.1);
            display: flex;
            flex-direction: column;
        }
        .messages {
            flex: 1;
            padding: 20px;
            overflow-y: auto;
            max-height: 400px;
        }
        .message {
            padding: 10px 15px;
            border-radius: 20px;
            margin-bottom: 10px;
            max-width: 75%;
            display: inline-block;
            clear: both;
        }
        .user {
            background: #0084ff;
            color: white;
            float: right;
            text-align: right;
        }
        .bot {
            background: #e4e6eb;
            color: black;
            float: left;
            text-align: left;
        }
        form {
            display: flex;
            border-top: 1px solid #ccc;
        }
        input[name="message"] {
            flex: 1;
            padding: 12px;
            border: none;
            border-radius: 0 0 0 10px;
        }
        input[type="submit"] {
            background: #0084ff;
            color: white;
            border: none;
            padding: 0 20px;
            border-radius: 0 0 10px 0;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="chat-box">
        <div class="messages">
            {% if user_message %}
                <div class="message user">{{ user_message }}</div>
            {% endif %}
            {% if response %}
                <div class="message bot">{{ response }}</div>
            {% endif %}
        </div>
        <form method="post">
            <input name="message" placeholder="Nhập tin nhắn..." autocomplete="off" required/>
            <input type="submit" value="Gửi"/>
        </form>
    </div>
</body>
</html>
"""

# Tạo ứng dụng Flask
@app.route("/", methods=["GET", "POST"])
def chatbot():
    response = ""
    user_message = ""
    if request.method == "POST":
      user_message = request.form["message"]
      X_input = vectorizer.transform([user_message])
      intent = clf.predict(X_input)[0]
      response = intent_responses.get(intent, "🤖 Xin lỗi, tôi chưa hiểu câu hỏi.")
    return render_template_string(HTML_TEMPLATE, user_message=user_message, response=response)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
app.run()
